version: '3.8'
services:
  chroma-db:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma
    restart: always

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
    volumes:
      - n8n-data:/home/node/.n8n
    restart: always

  embedding-api:
    build: ./scripts/api
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: always

volumes:
  chroma-data:
  n8n-data:
